### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by xx0red** [yaleman/crowdstrike_api#2]
There's no readme to show how to use the script. If you'd be kind enough to provide some insight on the available commands, etc. that would be great. I'm mainly using this for the RTR side of crowdstrike.

Thanks!

**Comment by yaleman** [comment]
Hi, this is very much in early development and a personal thing which I develop as I need it, RTR I haven't developed much for other than starting and deleting a session.

**Comment by xx0red** [comment]
Ah I gotcha.

**Comment by yaleman** [comment]
There's some more RTR functionality there now, give it a go - there's test code in the test_rtr.py script which you should be able to use for examples. :)

**Comment by xx0red** [comment]
Sweet! Thanks for doing that!
